server:
  port: ${PORT:0}

spring:
  application:
    name: api-catalog

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
    defaultZone: http://localhost:8761/eureka