server:
  port: ${PORT:0}

idRandom: ${random.value}

spring:
  application:
    name: api-movie

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: 29031999

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceURL:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}